### ISSUE TITLE
nable to locate element: {"method":"id","selector":"navLoginBtn"}

### ISSUE THREAD

**Issue by 121786404** [aialin/dl_icourse163#2]
$ python dl_icourse163_selenium.py
Traceback (most recent call last):
  File "dl_icourse163_selenium.py", line 175, in <module>
    icourse.login()
  File "dl_icourse163_selenium.py", line 19, in login
    self._driver.find_element_by_id('navLoginBtn').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 282, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 784, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"navLoginBtn"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.8.0-46-generic x86_64)

**Comment by 121786404** [comment]
url = 'http://www.icourse163.org/category/all/'
        self._driver= webdriver.Chrome()
        self._driver.get(url)
        self._driver.find_element_by_css_selector('a[class="f-f0 navLoginBtn"]').click()


改成这样可以下载了：
感谢！！

**Comment by aialin** [comment]
应该是登录页面的标签属性改了，所以通过id找不到，感谢～

**Comment by 121786404** [comment]
url = 'http://www.icourse163.org/category/all/'
这一句你没有改啊

**Comment by aialin** [comment]
我回错了。。编辑掉
